services:
    core-verification:
        image: registry.gitlab.com/vibrantnet/ryp/core-verification:latest
        restart: on-failure
        environment:
            - DB_SYNC_POSTGRES_URL=jdbc:postgresql://cardano-db-sync-postgres:5432/cexplorer
            - DB_SYNC_POSTGRES_USER=postgres
            - INDEXER_TYPE=cardano-db-sync
            - BLOCKFROST_URL=
        logging:
            driver: "json-file"
            options:
                max-size: "100m"
                max-file: "10"

    core-subscription:
        image: registry.gitlab.com/vibrantnet/ryp/core-subscription:latest
        restart: on-failure
        environment:
            - RYP_POSTGRES_URL=jdbc:postgresql://postgres:5432/ryp
            - RYP_POSTGRES_USER=postgres
        logging:
            driver: "json-file"
            options:
                max-size: "100m"
                max-file: "10"

    core-publishing:
        image: registry.gitlab.com/vibrantnet/ryp/core-publishing:latest
        restart: on-failure
        logging:
            driver: "json-file"
            options:
                max-size: "100m"
                max-file: "10"

    core-events:
        image: registry.gitlab.com/vibrantnet/ryp/core-events:latest
        restart: on-failure
        environment:
            - DB_SYNC_POSTGRES_URL=jdbc:postgresql://cardano-db-sync-postgres:5432/cexplorer
            - DB_SYNC_POSTGRES_USER=postgres
            - INDEXER_TYPE=cardano-db-sync
            - BLOCKFROST_URL=
        logging:
            driver: "json-file"
            options:
                max-size: "100m"
                max-file: "10"

    core-redirect:
        image: registry.gitlab.com/vibrantnet/ryp/core-redirect:latest
        restart: on-failure
        logging:
            driver: "json-file"
            options:
                max-size: "100m"
                max-file: "10"

    core-points:
        image: registry.gitlab.com/vibrantnet/ryp/core-points:latest
        restart: on-failure
        environment:
            - RYP_POSTGRES_URL=jdbc:postgresql://postgres:5432/ryp
            - RYP_POSTGRES_USER=postgres
        logging:
            driver: "json-file"
            options:
                max-size: "100m"
                max-file: "10"

    core-billing:
        image: registry.gitlab.com/vibrantnet/ryp/core-billing:latest
        restart: on-failure
        environment:
            - RYP_POSTGRES_URL=jdbc:postgresql://postgres:5432/ryp
            - RYP_POSTGRES_USER=postgres
        logging:
            driver: "json-file"
            options:
                max-size: "100m"
                max-file: "10"

    integration-discord:
        image: registry.gitlab.com/vibrantnet/ryp/integration-discord:latest
        restart: on-failure
        environment:
            - RABBITMQ_USER=ryp
            - RABBITMQ_HOST=rabbitmq
        logging:
            driver: "json-file"
            options:
                max-size: "100m"
                max-file: "10"

    integration-twilio:
        image: registry.gitlab.com/vibrantnet/ryp/integration-twilio:latest
        restart: on-failure
        environment:
            - RABBITMQ_USER=ryp
            - RABBITMQ_HOST=rabbitmq
        ports:
            - "3010:3000"
        logging:
            driver: "json-file"
            options:
                max-size: "100m"
                max-file: "10"

    integration-webpush:
        image: registry.gitlab.com/vibrantnet/ryp/integration-webpush:latest
        restart: on-failure
        environment:
            - RABBITMQ_USER=ryp
            - RABBITMQ_HOST=rabbitmq
        logging:
            driver: "json-file"
            options:
                max-size: "100m"
                max-file: "10"

    integration-sendgrid:
        image: registry.gitlab.com/vibrantnet/ryp/integration-sendgrid:latest
        restart: on-failure
        environment:
            - RABBITMQ_USER=ryp
            - RABBITMQ_HOST=rabbitmq
        logging:
            driver: "json-file"
            options:
                max-size: "100m"
                max-file: "10"

    integration-telegram:
        image: registry.gitlab.com/vibrantnet/ryp/integration-telegram:latest
        restart: on-failure
        environment:
            - RABBITMQ_USER=ryp
            - RABBITMQ_HOST=rabbitmq
        logging:
            driver: "json-file"
            options:
                max-size: "100m"
                max-file: "10"

    rabbitmq:
        image: rabbitmq:3-management
        environment:
            - RABBITMQ_DEFAULT_USER=ryp

    redis:
        image: redis:7.2.4-alpine
        command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
        volumes:
            - ./example/docker/redis.conf:/usr/local/etc/redis/redis.conf

    redisdata:
        image: redislabs/redisinsight:latest

    postgres:
        image: postgres:16.2-alpine
        environment:
            - POSTGRES_LOGGING=true
            - POSTGRES_DB=ryp
            - POSTGRES_USER=postgres
        volumes:
            - ./.docker-data/postgres:/var/lib/postgresql/data
            - ./core-subscription/src/main/resources/schema-postgres.sql:/docker-entrypoint-initdb.d/init.sql
        restart: unless-stopped
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"

    mongo:
        image: mongo:latest
        environment:
            - MONGO_INITDB_ROOT_USERNAME=ryp-root-user
        volumes:
            - ./.docker-data/mongo/db:/data/db
