version: "3.3"

services:
    core-verification:
        image: core-verification:latest
        container_name: core_verification_dev
        environment:
            - DB_SYNC_POSTGRES_URL=jdbc:postgresql://cardano-db-sync-postgres:5432/cexplorer
            - DB_SYNC_POSTGRES_PASSWORD=
            - BLOCKFROST_URL=https://cardano-mainnet.blockfrost.io/api/v0
            - BLOCKFROST_PROJECT_ID=
        ports:
            - "8070:8070"

    core-subscription:
        image: core-subscription:latest
        container_name: core_subscription_dev
        environment:
            - RYP_POSTGRES_PASSWORD=
        ports:
            - "8071:8071"

    core-publishing:
        image: core-publishing:latest
        container_name: core_publishing_dev
        ports:
            - "8072:8072"

    rabbitmq:
        container_name: ryp_rabbitmq_dev
        environment:
            - RABBITMQ_DEFAULT_PASS=lovuD7PqR17BLgpDCVzn
        ports:
            - "8081:15672"
            - "5672:5672"

    redis:
        container_name: redis_dev
        ports:
            - "6379:6379"

    redisdata:
        container_name: redisinsight_dev
        ports:
            - "8001:8001"
