version: "3.3"

services:
    core-verification:

        container_name: core_verification_prod
        environment:
            - DB_SYNC_POSTGRES_URL=jdbc:postgresql://cardano-db-sync-postgres:5432/cexplorer
            - DB_SYNC_POSTGRES_PASSWORD=
            - BLOCKFROST_URL=https://cardano-mainnet.blockfrost.io/api/v0
            - BLOCKFROST_PROJECT_ID=
            - RABBITMQ_PASSWORD=
        ports:
            - "8070:8070"

    core-subscription:

        container_name: core_subscription_prod
        environment:
            - RYP_POSTGRES_PASSWORD=
            - RABBITMQ_PASSWORD=



    core-publishing:

        container_name: core_publishing_prod
        environment:
            - RABBITMQ_PASSWORD=



    integration-discord:

        container_name: integration_discord_prod
        environment:
            - RABBITMQ_PASSWORD=

    integration-twilio:

        container_name: integration_twilio_prod
        environment:
            - RABBITMQ_PASSWORD=
            - TWILIO_ACCOUNT_SID=
            - TWILIO_AUTH_TOKEN=
            - TWILIO_VERIFY_SERVICE_SID=

    integration-webpush:

        container_name: integration_webpush_prod
        environment:
            - RABBITMQ_PASSWORD=
            - VAPID_PUBLIC_KEY=
            - VAPID_PRIVATE_KEY=
            - VAPID_SUBJECT=
            - PUBLIC_RYP_SITE=

    rabbitmq:
        container_name: ryp_rabbitmq_prod
        environment:
            - RABBITMQ_DEFAULT_PASS=




    redis:
        container_name: ryp_redis_prod



    redisdata:
        container_name: ryp_redisinsight_prod



    postgres:
        container_name: ryp_postgres_prod
        environment:
            - POSTGRES_PASSWORD=
        ports:
            - "5434:5432"

    mongo:
        container_name: ryp_mongo_prod