openapi: 3.1.0
x-stoplight:
  id: 7h3w556doa4lw
info:
  title: Core Publishing Service
  version: '1.0'
  description: The API for the core publishing service of the Cardano Blockchain announcement and notification application "Reach Your People"
  contact:
    name: Nils Codes
    url: 'https://vibrantnet.io'
    email: contact@vibrantnet.io
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
servers:
  - url: 'http://localhost:8072'
    description: Local Build
paths:
  '/projects/{projectId}/announcements':
    parameters:
      - $ref: ./common-schemas.yaml#/components/parameters/projectId
    get:
      summary: List announcements for a specific project
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Announcement'
                  x-stoplight:
                    id: nt5apw86n356b
                readOnly: true
      operationId: listAnnouncementsForProject
      description: 'List all announcements that a specific project has published, regardless of target.'
    post:
      summary: Publish new announcement for a specific project
      tags: []
      responses:
        '201':
          description: Created
      operationId: publishAnnouncementForProject
      x-stoplight:
        id: pdvltrzrnflha
      requestBody:
        description: Can be either a JSON object with the required data or the raw Activity Streams 2.0 Announcement JSON body
        required: true
        content:
          application/activity+json:
            schema:
              $ref: ./common-schemas.yaml#/components/schemas/ActivityStreamsAnnouncement
            examples:
              Example 1:
                value:
                  '@context': 'https://www.w3.org/ns/activitystreams'
                  type: Announce
                  actor:
                    type: Person
                    id: 'http://example.org/person/1234'
                  content: This is an announcement content.
                  to:
                    - 'https://example.org/followers/janedoe'
                  published: '2023-12-25T12:00:00Z'
                  summary: New Year Celebration
              Example 2:
                value:
                  '@context': 'https://www.w3.org/ns/activitystreams'
                  summary: We are proud to present our new roadmap to all our delegators!
                  content: Super long roadmap explanation...
                  type: Announce
                  actor:
                    type: Group
                    id: 'https://www.hazelpool.com'
                    name: HAZEL Stakepool
                  object:
                    type: Arrive
                    actor: 'https://www.hazelpool.com'
                    location:
                      type: Page
                      name: HAZEL 2024 Roadmap
                      url: 'https://hazelpool.com/roadmap'
          application/json:
            schema:
              $ref: '#/components/schemas/BasicAnnouncement'
      description: 'Publish an announcement for a project, token policy, SPO, dRep or social media account to all verified holders that have subscribed to updates, without exposing any social media or messaging identifiers to the publisher.'
  '/projects/{projectId}/roles/{accountId}':
    parameters:
      - $ref: ./common-schemas.yaml#/components/parameters/projectId
      - $ref: ./common-schemas.yaml#/components/parameters/accountId
    get:
      summary: Get the publishing role status
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublishingPermissions'
      operationId: getPublishingPermissionsForAccount
      description: Get the roles and permissions to publishing rights for a project and the related policies and assets.
      x-stoplight:
        id: 4v9i9vsh3w029
  '/announcements/{announcementId}':
    parameters:
      - $ref: ./common-schemas.yaml#/components/parameters/announcementId
    get:
      summary: Get announcement by ID
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Announcement'
      operationId: getAnnouncementById
      x-stoplight:
        id: 2bracyiadlely
      description: Get an announcement and its details and status by announcement UUID
  '/accounts/{accountId}/externalaccounts/{externalAccountId}/test':
    parameters:
      - $ref: ./common-schemas.yaml#/components/parameters/accountId
      - $ref: ./common-schemas.yaml#/components/parameters/externalAccountId
    post:
      summary: Send test announcement to account
      tags: []
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BasicAnnouncement'
          headers:
            Location:
              schema:
                type: string
              description: URL to retrieve the status of the test announcement
      operationId: sendTestAnnouncement
tags:
  - name: publishing
    description: Related to publishing content for subscribers
components:
  schemas:
    BasicAnnouncement:
      title: BasicAnnouncement
      x-stoplight:
        id: x6zlpg24qirgm
      type: object
      examples:
        - author: 1
          title: My important announcement
          content: "All the details that are extremely relevant\n\nAlso some other text, separately. Even emojis \U0001F49A"
          externalLink: 'https://ryp.io'
      required:
        - author
        - title
        - content
      properties:
        id:
          type: string
          x-stoplight:
            id: d7kmpv0pcy8uh
          format: uuid
          readOnly: true
        author:
          type: integer
          format: int64
          description: The subscription service account ID of the user account submitting the announcement
        title:
          type: string
          x-stoplight:
            id: 82aep8cn4pgb4
        content:
          type: string
          x-stoplight:
            id: fs9how9y3td4u
        externalLink:
          type: string
          x-stoplight:
            id: zwxkh3my3ukke
        policies:
          type: array
          description: 'If for a token-based project, the list of policy IDs to publish to.'
          items:
            $ref: ./common-schemas.yaml#/components/schemas/TokenPolicyId
            x-stoplight:
              id: p55cb7tf2uzhm
        stakepools:
          type: array
          description: 'If for a project containing stake pools, the pool hashes to publish to.'
          items:
            $ref: ./common-schemas.yaml#/components/schemas/StakepoolHash
        type:
          x-stoplight:
            id: pqmcs1vtsuj7m
          enum:
            - STANDARD
            - TEST
          default: 'STANDARD'
    Announcement:
      title: Announcement
      x-stoplight:
        id: tn0kcqwaq5n3i
      type: object
      required:
        - id
        - projectId
        - announcement
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
          x-stoplight:
            id: 59y15mti42gy0
        projectId:
          type: integer
          format: int64
        announcement:
          $ref: ./common-schemas.yaml#/components/schemas/ActivityStreamsAnnouncement
          x-stoplight:
            id: fmyvypl0l0lq2
        status:
          x-stoplight:
            id: ip54hu9noazge
          enum:
            - PREPARED
            - PENDING
            - PUBLISHING
            - PUBLISHED
            - CANCELLED
          readOnly: true
        shortLink:
          type: string
          readOnly: true
        audience:
          $ref: '#/components/schemas/Audience'
        statistics:
          $ref: '#/components/schemas/Statistics'
          readOnly: true
        createdDate:
          type: string
          format: date-time
          example: '2020-05-02T14:00:00Z'
          readOnly: true
          x-stoplight:
            id: 69yadbjcy1gme
        modifiedDate:
          type: string
          format: date-time
          example: '2020-05-02T14:00:00Z'
          readOnly: true
          x-stoplight:
            id: lk2x27snn91yc
    PublishingPermissions:
      title: PublishingPermissions
      x-stoplight:
        id: r37n11y922zxw
      type: object
      required:
        - accountId
        - policies
      properties:
        policies:
          x-stoplight:
            id: eh7mlah1i8mvu
          type: array
          items:
            $ref: '#/components/schemas/PolicyPublishingPermission'
            x-stoplight:
              id: gr4ykz2xqf2vd
        accountId:
          type: integer
          x-stoplight:
            id: 808hetlu258fu
          format: int64
          readOnly: true
    PolicyPublishingPermission:
      title: PolicyPublishingPermission
      x-stoplight:
        id: bj6n4zs9red9r
      type: object
      required:
        - policyId
        - permission
      properties:
        policyId:
          $ref: ./common-schemas.yaml#/components/schemas/TokenPolicyId
          x-stoplight:
            id: s5oe4ggco0ift
        permission:
          x-stoplight:
            id: 5epy3yroxy5mc
          enum:
            - PUBLISHING_MANUAL
            - PUBLISHING_CIP66
    Statistics:
      title: Statistics
      type: object
      properties:
        sent:
          type: object
          additionalProperties:
            type: integer
            format: int64
        uniqueAccounts:
          type: integer
          format: int64
          nullable: true
        explicitSubscribers:
          type: integer
          format: int64
          nullable: true
        delivered:
          type: object
          additionalProperties:
            type: integer
            format: int64
        failures:
          type: object
          additionalProperties:
            type: integer
            format: int64
        views:
          type: object
          additionalProperties:
            type: integer
            format: int64
    Audience:
      title: Audience
      x-stoplight:
        id: 614pi5dhms0ng
      type: object
      properties:
        policies:
          type: array
          description: 'If for a token-based project, the list of policy IDs this announcement was published to.'
          items:
            $ref: ./common-schemas.yaml#/components/schemas/TokenPolicyId
            x-stoplight:
              id: p55cb7tf2uzhm
