openapi: 3.1.0
x-stoplight:
  id: vxosojp7gbe4n
info:
  title: Core Subscription Service
  version: '1.0'
  contact:
    name: Nils Codes
    url: 'https://vibrantnet.io'
    email: contact@vibrantnet.io
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
  description: The API for the core subscription management service of the Cardano Blockchain announcement and notification application "Reach Your People"
servers:
  - url: 'http://localhost:8071'
    description: Local Build
paths:
  /accounts:
    post:
      summary: Create New Account
      operationId: createAccount
      responses:
        '201':
          description: Account Created
          content:
            application/json:
              schema:
                $ref: ./common-schemas.yaml#/components/schemas/Account
              examples:
                New Account for Jim Jergens:
                  value:
                    id: 12
                    createTime: '2024-02-18T11:15:09.618911-08:00'
                    displayName: Jim Jergens
        '400':
          description: Missing Required Information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: ./common-schemas.yaml#/components/schemas/Account
        description: Post the necessary fields for the API to create a new user.
      description: Create a new account.
      x-stoplight:
        id: osfbv5epro02s
  '/accounts/{accountId}':
    parameters:
      - $ref: ./common-schemas.yaml#/components/parameters/accountId
    get:
      summary: Get Account Info by numeric ID
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: ./common-schemas.yaml#/components/schemas/Account
        '404':
          description: User Not Found
      operationId: getAccountById
      description: Retrieve the information of the account with the matching account ID.
      x-stoplight:
        id: paz9atrd81lb3
    patch:
      summary: Update Account Information
      operationId: updateAccountById
      responses:
        '200':
          description: Account Updated
          content:
            application/json:
              schema:
                $ref: ./common-schemas.yaml#/components/schemas/Account
              examples:
                Updated User Jim Jergens:
                  value:
                    id: 12
                    displayName: Jim Jergens
        '404':
          description: User Not Found
        '409':
          description: Email Already Taken
      description: Update the information of an existing user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: ./common-schemas.yaml#/components/schemas/AccountPartial
        description: Patch user properties to update.
      x-stoplight:
        id: hub7c9md2sodt
  /externalaccounts:
    post:
      summary: Create External Account
      operationId: createExternalAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: ./common-schemas.yaml#/components/schemas/ExternalAccount
      responses:
        '201':
          description: External account data
          content:
            application/json:
              schema:
                $ref: ./common-schemas.yaml#/components/schemas/ExternalAccount
  '/externalaccounts/{providerType}/{referenceId}':
    parameters:
      - $ref: ./common-schemas.yaml#/components/parameters/providerType
      - $ref: ./common-schemas.yaml#/components/parameters/referenceId
    get:
      summary: Find External Account by Provider
      tags: []
      responses:
        '200':
          description: A matching external account for the provider/reference ID combination provided.
          content:
            application/json:
              schema:
                $ref: ./common-schemas.yaml#/components/schemas/ExternalAccount
        '404':
          description: No external account under that provider type and reference ID was found.
      operationId: findExternalAccountByProviderAndReferenceId
      x-stoplight:
        id: nzuvr98kjth4m
      description: 'Look up an external account by provider and the corresponding reference ID, to see if the external account is used somewhere, without knowing the internal ID.'
  '/accounts/{providerType}/{referenceId}':
    parameters:
      - $ref: ./common-schemas.yaml#/components/parameters/providerType
      - $ref: ./common-schemas.yaml#/components/parameters/referenceId
    get:
      summary: Find Account by External Account Provider
      tags: []
      responses:
        '200':
          description: A matching account for the provider/reference ID combination provided.
          content:
            application/json:
              schema:
                $ref: ./common-schemas.yaml#/components/schemas/Account
        '404':
          description: No account under that provider type and reference ID was found.
      operationId: findAccountByProviderAndReferenceId
      description: 'Look up an account by provider and the corresponding reference ID, to see if the account is used somewhere, without knowing the internal ID of the linked OWNER account'
  '/accounts/{accountId}/externalaccounts':
    parameters:
      - $ref: ./common-schemas.yaml#/components/parameters/accountId
    get:
      summary: Show linked external accounts
      tags: []
      responses:
        '200':
          description: List of linked external accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./common-schemas.yaml#/components/schemas/LinkedExternalAccount
                  x-stoplight:
                    id: 7grhvhy96bjob
      operationId: getLinkedExternalAccounts
      x-stoplight:
        id: j8re5pa662xoi
  '/accounts/{accountId}/subscriptions':
    parameters:
      - $ref: ./common-schemas.yaml#/components/parameters/accountId
    get:
      summary: Get all subscriptions for an account
      tags: []
      responses: {}
      operationId: getAllSubscriptionsForAccount
      x-stoplight:
        id: avvc7tu7x8sio
    post:
      summary: Add new subscription for this account
      tags: []
      responses: {}
      operationId: subscribeAccountToProject
      x-stoplight:
        id: p22i1rs402yq3
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: ./common-schemas.yaml#/components/schemas/NewSubscription
  '/accounts/{accountId}/externalaccounts/{externalAccountId}':
    parameters:
      - $ref: ./common-schemas.yaml#/components/parameters/accountId
      - $ref: ./common-schemas.yaml#/components/parameters/externalAccountId
    put:
      summary: Link existing external account
      tags: []
      responses:
        '200':
          description: The linked external account
          content:
            application/json:
              schema:
                $ref: ./common-schemas.yaml#/components/schemas/LinkedExternalAccount
      operationId: linkExternalAccount
      x-stoplight:
        id: mjt84x6rlvvgr
      description: Links an existing external account to this account (if possible)
    delete:
      summary: Unlink external account
      tags: []
      responses:
        '204':
          description: Unlinking successful
      operationId: unlinkExternalAccount
      x-stoplight:
        id: pgxcykih0shh0
      description: Unlink the external account from this account
  '/accounts/{accountId}/projects':
    parameters:
      - $ref: ./common-schemas.yaml#/components/parameters/accountId
    get:
      summary: Get projects owned by this account
      tags: []
      responses:
        '200':
          description: All owned projects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./common-schemas.yaml#/components/schemas/Project
                  x-stoplight:
                    id: u60wcuub5mul0
      operationId: getProjectsForAccount
      description: Get all projects that this account is an owner of.
      x-stoplight:
        id: 23i2524rwj2xv
  /projects:
    post:
      summary: Add new project
      operationId: addNewProject
      tags: []
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ./common-schemas.yaml#/components/schemas/Project
        '400':
          description: Missing Required Information
      x-stoplight:
        id: 34me4vayijrkk
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: ./common-schemas.yaml#/components/schemas/Project
      parameters:
        - schema:
            type: integer
            format: int64
          in: query
          name: projectOwner
          description: Account ID of the owner of the project
    get:
      summary: List all projects
      tags: []
      responses:
        '200':
          description: List of all available projects
          content:
            application/json:
              schema:
                $ref: ./common-schemas.yaml#/components/schemas/Project
      operationId: listProjects
      x-stoplight:
        id: j8vk041jr9ctw
  '/projects/{projectId}/subscriptions':
    parameters:
      - $ref: ./common-schemas.yaml#/components/parameters/projectId
    get:
      summary: Get all subscription for a project
      tags: []
      responses: {}
      operationId: getAllSubscriptionsForProject
      x-stoplight:
        id: oom60rtr3642b
  /subscriptions/global:
    get:
      summary: Get global subscriptions
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./common-schemas.yaml#/components/schemas/Subscription
                  x-stoplight:
                    id: kshusczjoik1g
      operationId: getGlobalSubscriptions
      x-stoplight:
        id: candiq0d6nerz
      description: Get all subscriptions that are global and as such relate to everything that occurs to projects related in an account's wallet.
tags:
  - name: subscription
    description: Related to subscribing to announcements
