openapi: 3.1.0
x-stoplight:
  id: 4wr8ecqlisr5o
info:
  title: Core Verification Service
  version: '1.0'
  contact:
    name: Nils Codes
    url: 'https://vibrantnet.io'
    email: contact@vibrantnet.io
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
  description: The API for the core verification service of the Cardano Blockchain announcement and notification application "Reach Your People"
servers:
  - url: 'http://localhost:8070'
    description: Local Build
components:
  schemas: {}
tags:
  - name: verification
    description: Related to verification of subscriber and publisher accounts
