integration-discord-docker:
    rules:
        - if: $CI_COMMIT_BRANCH == "main"
        - if: $CI_PIPELINE_SOURCE == "web"
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
          changes:
              - "integrations/discord/**/*"
              - ".gitlab-ci.yml"
    image: docker:latest
    stage: docker
    services:
        - docker:dind
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    script:
        - cd integrations/discord
        - |
            if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
              tag=""
              echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
            else
              tag=":$CI_COMMIT_REF_SLUG"
              echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
            fi
        - docker build --pull -t "$CI_REGISTRY_IMAGE/integration-discord${tag}" .
        - docker push "$CI_REGISTRY_IMAGE/integration-discord${tag}"

integration-discord-dependency-check:
    image: node:22
    stage: test
    rules:
        - if: $CI_COMMIT_BRANCH == "main"
        - if: $CI_PIPELINE_SOURCE == "web"
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    script:
        - cd integrations/discord
        - npm install --save-dev audit-ci
        - npx audit-ci --config .audit-ci.json
